mdapi/src/objects/Expense_Report__c.object
<CustomObject>
    <label>Expense Report</label>
    <nameField>
        <label>Expense Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <description>sum amount of all expense items</description>
        <label>Amount</label>
        <summarizedField>Expense_Item__c.Reimbursable_amount__c</summarizedField>
        <summaryForeignKey>Expense_Item__c.Expense_Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ExpenseReportSharingTest.cls
@isTest
private class  ExpenseReportSharingTest {

    @isTest
    static void whenProfileIsFinanceCanGetAllExpenseReports() {

        Expense_Report__c anothers = new Expense_Report__c(
            Name = 'Show me their money',
            Amount__c = 100
        );
        insert anothers;
        
        User user = [SELECT Id
                    FROM User
                    WHERE Profile.Name = 'Finance'
                    LIMIT 1];
        System.assert(user != null, 'User Exists');

        System.runAs(user) {
            Expense_Report__c mine = new Expense_Report__c(
                Name = 'Show me my money',
                Amount__c = 500
            );
            insert mine;

            Test.startTest();
            List<Expense_Report__c> saved = [
                SELECT Id
                FROM Expense_Report__c
            ];
            Test.stopTest();

            System.assertEquals(2, saved.size(), 'can see all the money');
        }
    }
    @isTest
    static void whenProfileIsConsultantCantGetAllExpenseReports() {
        
        Expense_Report__c anothers = new Expense_Report__c(
            Name = 'Show me their money',
            Amount__c = 100
        );
        insert anothers;
        
        User user = [SELECT Id
                    FROM User
                    WHERE Profile.Name = 'Consultant'
                    LIMIT 1];
        System.assert(user != null, 'User Exists');

        System.runAs(user) {
            Expense_Report__c mine = new Expense_Report__c(
                Name = 'Show me my money',
                Amount__c = 500
            );
            insert mine;

            Test.startTest();
            List<Expense_Report__c> saved = [
                SELECT Id
                FROM Expense_Report__c
            ];
            Test.stopTest();

            System.assert(!saved.contains(anothers) , 'can only see my money');
        }
    }
}