force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange_Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/src/objects/Expense_Category__c.object
<CustomObject>
    <label>Expense Category</label>
    <nameField>
        <label>Expense Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Reimbursable_Percentage__c</fullName>
        <description>Percentage of the total expense item amount that is reimbursable under this category</description>
        <label>Reimbursable Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

mdapi/src/objects/Expense_Item__c.object
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Currency amount of expense item</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>KYD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>ISK</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Currency exchange rate</description>
        <label>Exchange_Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Category</label>
        <referenceTo>Expense_Category__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reimbursable_amount__c</fullName>
        <label>Reimbursable_amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ExpenseItemTriggerHandler.cls
public class ExpenseItemTriggerHandler extends TriggerHandler {
    public static void AssignExchangeRate(List<Expense_Item__c> itemList) {
        List<Expense_Item__c> listToUpdate = new List<Expense_Item__c>();

        for (Expense_Item__c itemObj : itemList){
            if (itemObj.Currency__c == 'USD') {
                itemObj.Exchange_Rate__c = 1;
            } else {
                itemObj.Exchange_Rate__c = itemObj.Exchange_Rate__c;
            }
            listToUpdate.add(itemObj);
        }
    }

    public static void CalculateReimbursableAmount(List<Expense_Item__c> itemList){
        List<Expense_Item__c> listToUpdate = new List<Expense_Item__c>();

        Map<Id, Expense_Category__c> categories = new Map<Id, Expense_Category__c>([
          SELECT Id, Reimbursable_Percentage__c
          FROM Expense_Category__c
        ]);

        //    Expense_Category__c thisExpenseCategory = [ 
        //        SELECT 
        //        Id, 
        //        Reimbursable_Percentage__c 
        //        FROM Expense_Category__c 
        //        WHERE Id = :itemObj.Expense_Category__c  //WHERE Expense_Category__c in :expenseCategoryIds
        //     ];

        for (Expense_Item__c itemObj : itemList){
           itemObj.Reimbursable_amount__c = itemObj.Exchange_Rate__c * itemObj.Amount__c * (categories.get(itemObj.Expense_Category__c).Reimbursable_Percentage__c/100);
           listToUpdate.add(itemObj); 
        }
    }

    private void beforeInsert(List<Expense_Item__c> itemList) {
        AssignExchangeRate(itemList);
        CalculateReimbursableAmount(itemList);
    }
    
    private void beforeUpdate(List<Expense_Item__c> itemList) {
        AssignExchangeRate(itemList);
        CalculateReimbursableAmount(itemList);
    }

    private void beforeDelete(List<Expense_Item__c> itemList) { 
        //Not much going on here... 
    }

    private void afterInsert(List<Expense_Item__c> itemList) {
        //Not much going on here...
    }

    private void afterUpdate(List<Expense_Item__c> itemList) {
        //Not much going on here...
    }

    private void afterDelete(List<Expense_Item__c> itemList) {
        //Not much going on here...
    }
}