force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange_Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/src/objects/Expense_Item__c.object
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>KYD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>ISK</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Currency exchange rate</description>
        <label>Exchange_Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapi/src/classes/ExpenseItemTriggerHandler.cls
public class ExpenseItemTriggerHandler extends TriggerHandler {
    public static void AssignExchangeRate(List<Expense_Item__c> itemList) {
        List<Expense_Item__c> listToUpdate = new List<Expense_Item__c>();

        for (Expense_Item__c itemObj : itemList){
            if (itemObj.Currency__c == 'USD') {
                itemObj.Exchange_Rate__c = 1;
            } else {
                itemObj.Exchange_Rate__c = 0;
            }
            listToUpdate.add(itemObj);
        }
    }

    private void beforeInsert(List<Expense_Item__c> itemList) {
        AssignExchangeRate(itemList);
    }
    
    private void beforeUpdate(List<Expense_Item__c> itemList) {
        AssignExchangeRate(itemList);
    }

    private void beforeDelete(List<Expense_Item__c> itemList) { 
        //Not much going on here... 
    }

    private void afterInsert(List<Expense_Item__c> itemList) {
        //Not much going on here...
    }

    private void afterUpdate(List<Expense_Item__c> itemList) {
        //Not much going on here...
    }

    private void afterDelete(List<Expense_Item__c> itemList) {
        //Not much going on here...
    }
}