force-app/main/default/objects/Exchange_Rate__c/Exchange_Rate__c.object-meta.xml
<CustomObject>
    <label>Exchange Rate</label>
    <nameField>
        <label>Exchange_Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

mdapi/src/objects/Expense_Category__c.object
<CustomObject>
    <label>Expense Category</label>
    <nameField>
        <label>Expense Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Reimbursable_Percentage__c</fullName>
        <description>Percentage of the total expense item amount that is reimbursable under this category</description>
        <label>Reimbursable Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

mdapi/src/objects/Expense_Item__c.object
<CustomObject>
    <label>Expense Item</label>
    <nameField>
        <label>Expense Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Currency amount of expense item</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>KYD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>ISK</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>User can add date item was created</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exchange_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Currency exchange rate</description>
        <label>Exchange_Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expense Category</label>
        <referenceTo>Expense_Category__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expense_Report__c</fullName>
        <label>Expense Report</label>
        <referenceTo>Expense_Report__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reimbursable_amount__c</fullName>
        <label>Reimbursable_amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

mdapi/src/objects/Expense_Report__c.object
<CustomObject>
    <label>Expense Report</label>
    <nameField>
        <label>Expense Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
    <fields>
        <fullName>Amount__c</fullName>
        <description>sum amount of all expense items</description>
        <label>Amount</label>
        <summarizedField>Expense_Item__c.Reimbursable_amount__c</summarizedField>
        <summaryForeignKey>Expense_Item__c.Expense_Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ExpenseItemTriggerTest.cls
@isTest
public class ExpenseItemTriggerTest {
    @isTest
    public static void whenExpenseItemInsertedReimbursableAmountCorrect() {
        // select consultant into user 
        User user = [
            SELECT Id
            FROM User
            WHERE Profile.Name = 'Consultant'
            LIMIT 1
          ];
        System.assert(user != null, 'Consultant User Exists');

      System.runAs(user) {
        makeData();
        // save a new expense report
        Expense_Report__c expenseReport = new Expense_Report__c(
          Name = 'Test Expense Report'
        );

        insert expenseReport;

        // get category with reimbursable percent 1 and store in variable reimbursable100
        Expense_Category__c reimbursable100 = [
            SELECT Id
            FROM Expense_Category__c
            WHERE Reimbursable_Percentage__c = 100
            LIMIT 1
        ];
        // get category with reimbursable percent .5 and store in variable reimbursable50
        Expense_Category__c reimbursable50 = [
            SELECT Id
            FROM Expense_Category__c
            WHERE Reimbursable_Percentage__c = 50
            LIMIT 1
        ];
        // instantiate list of expense items to save later
        List<Expense_Item__c> expenseItems = new List<Expense_Item__c>();

        // instantiate a expense item itemJPY100 with currency JPY, category: reimbursable100, amount: 100, date: yesterday
        Expense_Item__c itemJPY100 = new Expense_Item__c(
          Expense_Report__c = expenseReport.Id,
          Expense_Category__c = reimbursable100.Id,
          Description__c = 'JPY 100',
          Date__c = System.today() - 1,
          Currency__c = 'JPY',
          Amount__c = 100
        );

        // add to list
        expenseItems.add(itemJPY100);

        // instantiate an expense item itemUSD100 with currency USD, category: reimbursable100, amount: 100, date: yesterday
        Expense_Item__c itemUSD100 = new Expense_Item__c(
          Expense_Report__c = expenseReport.Id,
          Expense_Category__c = reimbursable100.Id,
          Description__c = 'USD 100',
          Date__c = System.today() - 1,
          Currency__c = 'USD',
          Amount__c = 100
        );
        // add to list
        expenseItems.add(itemUSD100);

        // instantiate an expense item itemJPY50 with currency JPY, category: reimbursable50, amount:100, date: day before yesterday
        Expense_Item__c itemJPY50 = new Expense_Item__c(
          Expense_Report__c = expenseReport.Id,
          Expense_Category__c = reimbursable50.Id,
          Description__c = 'JPY 50',
          Date__c = System.today() - 2,
          Currency__c = 'JPY',
          Amount__c = 100
        );
        // add to list
        expenseItems.add(itemJPY50);

        // instantiate an expense item itemUSD50 with currency USD, category: reimbursable50, amount: 100, date: day before yesterday
        Expense_Item__c itemUSD50 = new Expense_Item__c(
          Expense_Report__c = expenseReport.Id,
          Expense_Category__c = reimbursable50.Id,
          Description__c = 'USD 50',
          Date__c = System.today() - 2,
          Currency__c = 'USD',
          Amount__c = 100
        ); 
        // add to list
        expenseItems.add(itemUSD50);

        Test.startTest();
        insert expenseItems;
        Test.stopTest();

        // select saved items and data to assert into a map for easy fetching by id
        Map<Id, Expense_Item__c> savedItems = new Map<Id, Expense_Item__c>([
          SELECT Id, Exchange_Rate__c, Reimbursable_Amount__c
          FROM Expense_Item__c
        ]);

        // TODO update test when fx rates are captured
        // get itemJPY100 by Id from the map
        // assert exchange rate is 0
        System.assertEquals(0, savedItems.get(itemJPY100.Id).Exchange_Rate__c, 'exchange rate is 0');
        // assert reimbursable amount is 0
        System.assertEquals(0, savedItems.get(itemJPY100.Id).Reimbursable_Amount__c, 'reimbursable amount is 0');
 
        // get itemUSD100 by Id from the map
        // assert exchange rate is 1
        System.assertEquals(1, savedItems.get(itemUSD100.Id).Exchange_Rate__c, 'exchange rate is 1');
        // assert reimbursable amount is 100
        System.assertEquals(100, savedItems.get(itemUSD100.Id).Reimbursable_Amount__c, 'reimbursable amount is 100');

        // TODO update test when fx rates are captured
        // get itemJPY50 by Id from the map
        // assert exchange rate is 0
        System.assertEquals(0, savedItems.get(itemJPY50.Id).Exchange_Rate__c, 'exchange rate is 0');
        // assert reimbursable amount is 0
         System.assertEquals(0, savedItems.get(itemJPY50.Id).Reimbursable_Amount__c, 'reimbursable amount is 0');

        // get itemUSD50 by Id from the map
        // assert exchange rate is 1
        System.assertEquals(1, savedItems.get(itemUSD50.Id).Exchange_Rate__c, 'exchange rate is 1');
        // assert reimbursable amount is 50
        System.assertEquals(50, savedItems.get(itemUSD50.Id).Reimbursable_Amount__c, 'reimbursable amount is 50');

      }
    }

    @isTest
    public static void whenExpenseItemUpdatedReimbursableAmountCorrect() {
       // select consultant into user 
        User user = [
            SELECT Id
            FROM User
            WHERE Profile.Name = 'Consultant'
            LIMIT 1
        ];
        System.assert(user != null, 'Consultant User Exists');

      System.runAs(user) {
        makeData();
        // save a new expense report
        Expense_Report__c expenseReport = new Expense_Report__c(
          Name = 'Test Expense Report'
        );

        insert expenseReport;

        Expense_Category__c reimbursable100 = [
            SELECT Id
            FROM Expense_Category__c
            WHERE Reimbursable_Percentage__c = 100
            LIMIT 1
        ];

        List<Expense_Item__c> updateExpenseItems = new List<Expense_Item__c>();

        Expense_Item__c itemJPY100 = new Expense_Item__c(
          Expense_Report__c = expenseReport.Id,
          Expense_Category__c = reimbursable100.Id,
          Description__c = 'JPY 100',
          Date__c = System.today() - 1,
          Currency__c = 'JPY',
          Amount__c = 100
        );

        Expense_Item__c itemUSD100 = new Expense_Item__c(
          Expense_Report__c = expenseReport.Id,
          Expense_Category__c = reimbursable100.Id,
          Description__c = 'USD 100',
          Date__c = System.today() - 1,
          Currency__c = 'USD',
          Amount__c = 100
        );

        updateExpenseItems.add(itemJPY100);
        updateExpenseItems.add(itemUSD100);

        Test.startTest();
        insert updateExpenseItems;

        itemJPY100.Currency__c='USD';
        itemUSD100.Currency__c='JPY';

        update updateExpenseItems;
        Test.stopTest();
      
        // select saved items and data to assert into a map for easy fetching by id
        Map<Id, Expense_Item__c> savedItems = new Map<Id, Expense_Item__c>([
          SELECT Id, Exchange_Rate__c, Reimbursable_Amount__c
          FROM Expense_Item__c
        ]);

        System.assertEquals(1, savedItems.get(itemJPY100.Id).Exchange_Rate__c, 'exchange rate is 1');
        System.assertEquals(0, savedItems.get(itemUSD100.Id).Exchange_Rate__c, 'exchange rate is 0');
        }
      // create test to verify when saved expense item is updated to USD from JPY, exchange rate changes from 0 to 1 
      // create test to verify when saved expense item is updated to JPY from USD, exchange rate changes from 1 to 0
     
    }

    @testSetup
    static void makeData() {
      List<Expense_Category__c > categories = new List<Expense_Category__c >();

      categories.add(new Expense_Category__c(
          Name = 'Gas',
          Reimbursable_Percentage__c = 100
      ));

      categories.add(new Expense_Category__c(
          Name = 'Dining',
          Reimbursable_Percentage__c = 50
      ));
      
      insert categories;
      // setup test 2 categories for each test
      // 100% and 50% reimbursable
      // practice bulkification
      // add categories to list
      // save list

    }
}